### ISSUE TITLE
Getting Error while starting the project

### ISSUE THREAD

**Issue by abdulbasit-tanhan** [THEOplayer/android-sdk-starter-project#3]
Hi I am getting error while starting the project.

`2020-10-05 02:11:20.357 7573-7573/com.theoplayer.theoplayerexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.theoplayer.theoplayerexample, PID: 7573
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.theoplayer.theoplayerexample/com.theoplayer.theoplayerexample.MainActivity}: android.view.InflateException: Binary XML file line #9 in com.theoplayer.theoplayerexample:layout/activity_main: Binary XML file line #9 in com.theoplayer.theoplayerexample:layout/activity_main: Error inflating class com.theoplayer.android.api.THEOplayerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3632)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: android.view.InflateException: Binary XML file line #9 in com.theoplayer.theoplayerexample:layout/activity_main: Binary XML file line #9 in com.theoplayer.theoplayerexample:layout/activity_main: Error inflating class com.theoplayer.android.api.THEOplayerView
     Caused by: android.view.InflateException: Binary XML file line #9 in com.theoplayer.theoplayerexample:layout/activity_main: Error inflating class com.theoplayer.android.api.THEOplayerView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.theoplayer.theoplayerexample.MainActivity.onCreate(MainActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:7957)
        at android.app.Activity.performCreate(Activity.java:7946)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3607)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2020-10-05 02:11:20.358 7573-7573/com.theoplayer.theoplayerexample E/AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/theoplayer/android/internal/fullscreen/FullScreenActivityImpl;
        at com.theoplayer.android.api.THEOplayerView.<init>(THEOplayerView.java:110)
        at com.theoplayer.android.api.THEOplayerView.<init>(THEOplayerView.java:190)
        	... 28 more
     Caused by: java.lang.ClassNotFoundException: com.theoplayer.android.internal.fullscreen.FullScreenActivityImpl
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 30 more
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/app/AppCompatActivity;
        	... 30 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.theoplayer.theoplayerexample-PLMnXpGs-GpxWCmUUbo_qA==/base.apk"],nativeLibraryDirectories=[/data/app/com.theoplayer.theoplayerexample-PLMnXpGs-GpxWCmUUbo_qA==/lib/arm, /data/app/com.theoplayer.theoplayerexample-PLMnXpGs-GpxWCmUUbo_qA==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 30 more`

**Comment by Danesz** [comment]
It complains about a dependency.

Please try to update the dependency on the Support Library to AndroidX.

From:

```
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
```

To:
```
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
```
